/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './contact.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/forms/src/form_builder';
import * as import9 from './contact-component.css.shim';
import * as import10 from '../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import11 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import13 from '../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import14 from '@angular/common/src/pipes/json_pipe';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/forms/src/directives/default_value_accessor';
import * as import17 from '@angular/forms/src/directives/control_value_accessor';
import * as import18 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import19 from '@angular/forms/src/directives/ng_control';
import * as import20 from '@angular/forms/src/directives/ng_control_status';
import * as import21 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import22 from '@angular/forms/src/directives/control_container';
export class Wrapper_ContactComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ContactComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.ContactComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ContactComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ContactComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ContactComponent>;
  _ContactComponent_0_3:Wrapper_ContactComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ContactComponent_Host0,renderType_ContactComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-contact',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ContactComponent0(this.viewUtils,this,0,this._el_0);
    this._ContactComponent_0_3 = new Wrapper_ContactComponent(this.injectorGet(import8.FormBuilder,this.parentIndex));
    this.compView_0.create(this._ContactComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ContactComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ContactComponent) && (0 === requestNodeIndex))) { return this._ContactComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ContactComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ContactComponentNgFactory:import7.ComponentFactory<import0.ContactComponent> = new import7.ComponentFactory<import0.ContactComponent>('app-contact',View_ContactComponent_Host0,import0.ContactComponent);
const styles_ContactComponent:any[] = [import9.styles];
var renderType_ContactComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ContactComponent,{});
export class View_ContactComponent0 extends import1.AppView<import0.ContactComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _FormGroupDirective_3_3:import10.Wrapper_FormGroupDirective;
  _ControlContainer_3_4:any;
  _NgControlStatusGroup_3_5:import11.Wrapper_NgControlStatusGroup;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _DefaultValueAccessor_9_3:import12.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_9_4:any[];
  _FormControlName_9_5:import13.Wrapper_FormControlName;
  _NgControl_9_6:any;
  _NgControlStatus_9_7:import11.Wrapper_NgControlStatus;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _DefaultValueAccessor_14_3:import12.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_14_4:any[];
  _FormControlName_14_5:import13.Wrapper_FormControlName;
  _NgControl_14_6:any;
  _NgControlStatus_14_7:import11.Wrapper_NgControlStatus;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _DefaultValueAccessor_19_3:import12.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_19_4:any[];
  _FormControlName_19_5:import13.Wrapper_FormControlName;
  _NgControl_19_6:any;
  _NgControlStatus_19_7:import11.Wrapper_NgControlStatus;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  /*private*/ _expr_63:any;
  _pipe_json_0:import14.JsonPipe;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ContactComponent0,renderType_ContactComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_63 = import6.UNINITIALIZED;
    this._expr_65 = import6.UNINITIALIZED;
    this._expr_66 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Contact Reactive Form',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'form',new import3.InlineArray2(2,'novalidate',''),(null as any));
    this._FormGroupDirective_3_3 = new import10.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_3_4 = this._FormGroupDirective_3_3.context;
    this._NgControlStatusGroup_3_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_3_4);
    this._text_4 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','form-content'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n      Name:\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'input',new import3.InlineArray8(8,'class','sd-form-control','formControlName','name','placeholder','Enter your name.','type','text'),(null as any));
    this._DefaultValueAccessor_9_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_9));
    this._NG_VALUE_ACCESSOR_9_4 = [this._DefaultValueAccessor_9_3.context];
    this._FormControlName_9_5 = new import13.Wrapper_FormControlName(this._ControlContainer_3_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_9_4);
    this._NgControl_9_6 = this._FormControlName_9_5.context;
    this._NgControlStatus_9_7 = new import11.Wrapper_NgControlStatus(this._NgControl_9_6);
    this._text_10 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_5,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n      Email:\n      ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'input',new import3.InlineArray8(8,'class','sd-form-control','formControlName','email','placeholder','Enter your email.','type','email'),(null as any));
    this._DefaultValueAccessor_14_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_14));
    this._NG_VALUE_ACCESSOR_14_4 = [this._DefaultValueAccessor_14_3.context];
    this._FormControlName_14_5 = new import13.Wrapper_FormControlName(this._ControlContainer_3_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_14_4);
    this._NgControl_14_6 = this._FormControlName_14_5.context;
    this._NgControlStatus_14_7 = new import11.Wrapper_NgControlStatus(this._NgControl_14_6);
    this._text_15 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_5,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n      Content:\n      ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'textarea',new import3.InlineArray8(6,'class','sd-form-control','formControlName','content','placeholder','Content here.'),(null as any));
    this._DefaultValueAccessor_19_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_19));
    this._NG_VALUE_ACCESSOR_19_4 = [this._DefaultValueAccessor_19_3.context];
    this._FormControlName_19_5 = new import13.Wrapper_FormControlName(this._ControlContainer_3_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_19_4);
    this._NgControl_19_6 = this._FormControlName_19_5.context;
    this._NgControlStatus_19_7 = new import11.Wrapper_NgControlStatus(this._NgControl_19_6);
    this._text_20 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_5,'div',new import3.InlineArray2(2,'class','form-submit'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'button',new import3.InlineArray2(2,'type','submit'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Submit',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._text_28 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','form-value'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n  Form value:\n  ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'pre',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n  ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_30,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'',(null as any));
    this._text_37 = this.renderer.createText(this._el_30,'\n  ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_30,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'',(null as any));
    this._text_40 = this.renderer.createText(this._el_30,'\n  ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_30,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Submit then open console to see full form.',(null as any));
    this._text_43 = this.renderer.createText(this._el_30,'\n',(null as any));
    this._text_44 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_3,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_3));
    this._FormGroupDirective_3_3.subscribe(this,this.eventHandler(this.handleEvent_3),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_14));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_19));
    this._pipe_json_0 = new import14.JsonPipe();
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.DefaultValueAccessor) && (9 === requestNodeIndex))) { return this._DefaultValueAccessor_9_3.context; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (9 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_9_4; }
    if (((token === import18.FormControlName) && (9 === requestNodeIndex))) { return this._FormControlName_9_5.context; }
    if (((token === import19.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_6; }
    if (((token === import20.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_7.context; }
    if (((token === import16.DefaultValueAccessor) && (14 === requestNodeIndex))) { return this._DefaultValueAccessor_14_3.context; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (14 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_14_4; }
    if (((token === import18.FormControlName) && (14 === requestNodeIndex))) { return this._FormControlName_14_5.context; }
    if (((token === import19.NgControl) && (14 === requestNodeIndex))) { return this._NgControl_14_6; }
    if (((token === import20.NgControlStatus) && (14 === requestNodeIndex))) { return this._NgControlStatus_14_7.context; }
    if (((token === import16.DefaultValueAccessor) && (19 === requestNodeIndex))) { return this._DefaultValueAccessor_19_3.context; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (19 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_19_4; }
    if (((token === import18.FormControlName) && (19 === requestNodeIndex))) { return this._FormControlName_19_5.context; }
    if (((token === import19.NgControl) && (19 === requestNodeIndex))) { return this._NgControl_19_6; }
    if (((token === import20.NgControlStatus) && (19 === requestNodeIndex))) { return this._NgControlStatus_19_7.context; }
    if (((token === import21.FormGroupDirective) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._FormGroupDirective_3_3.context; }
    if (((token === import22.ControlContainer) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ControlContainer_3_4; }
    if (((token === import20.NgControlStatusGroup) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._NgControlStatusGroup_3_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    const currVal_3_0_0:any = this.context.contactForm;
    this._FormGroupDirective_3_3.check_form(currVal_3_0_0,throwOnChange,false);
    this._FormGroupDirective_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    this._NgControlStatusGroup_3_5.ngDoCheck(this,this._el_3,throwOnChange);
    this._DefaultValueAccessor_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_9_1_0:any = 'name';
    this._FormControlName_9_5.check_name(currVal_9_1_0,throwOnChange,false);
    this._FormControlName_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    this._NgControlStatus_9_7.ngDoCheck(this,this._el_9,throwOnChange);
    this._DefaultValueAccessor_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    const currVal_14_1_0:any = 'email';
    this._FormControlName_14_5.check_name(currVal_14_1_0,throwOnChange,false);
    this._FormControlName_14_5.ngDoCheck(this,this._el_14,throwOnChange);
    this._NgControlStatus_14_7.ngDoCheck(this,this._el_14,throwOnChange);
    this._DefaultValueAccessor_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    const currVal_19_1_0:any = 'content';
    this._FormControlName_19_5.check_name(currVal_19_1_0,throwOnChange,false);
    this._FormControlName_19_5.ngDoCheck(this,this._el_19,throwOnChange);
    this._NgControlStatus_19_7.ngDoCheck(this,this._el_19,throwOnChange);
    this._NgControlStatusGroup_3_5.checkHost(this,this,this._el_3,throwOnChange);
    this._NgControlStatus_9_7.checkHost(this,this,this._el_9,throwOnChange);
    this._NgControlStatus_14_7.checkHost(this,this,this._el_14,throwOnChange);
    this._NgControlStatus_19_7.checkHost(this,this,this._el_19,throwOnChange);
    valUnwrapper.reset();
    const currVal_63:any = import3.inlineInterpolate(1,'    ',valUnwrapper.unwrap(this._pipe_json_0.transform(this.context.contactForm.value)),'\n  ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_63,currVal_63))) {
      this.renderer.setText(this._text_33,currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_65:any = import3.inlineInterpolate(1,'\n    Status: ',this.context.contactForm.status,'\n  ');
    if (import3.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setText(this._text_36,currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:any = import3.inlineInterpolate(1,'\n    Valid: ',this.context.contactForm.valid,'\n  ');
    if (import3.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setText(this._text_39,currVal_66);
      this._expr_66 = currVal_66;
    }
  }
  destroyInternal():void {
    this._FormControlName_9_5.ngOnDestroy();
    this._FormControlName_14_5.ngOnDestroy();
    this._FormControlName_19_5.ngOnDestroy();
    this._FormGroupDirective_3_3.ngOnDestroy();
  }
  handleEvent_3(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_3_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.submitForm()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_9_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_14_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_19_3.handleEvent(eventName,$event) && result);
    return result;
  }
}