/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.form-content[_ngcontent-%COMP%] {\n  width: 90%;\n  max-width: 600px;\n  margin: 0 auto;\n}\n.form-content[_ngcontent-%COMP%]   .sd-form-control[_ngcontent-%COMP%] {\n  display: block;\n  margin-bottom: 10px;\n  width: 100%;\n  padding: 10px;\n}\n.form-content[_ngcontent-%COMP%]   textarea.sd-form-control[_ngcontent-%COMP%] {\n  max-width: 100%;\n}'];